### PR TITLE
Firecrown example

### PR DESCRIPTION
**Pull request by ellongley**
This pull request is to add a notebook that looks at the outputs from running the Firecrown DES 3x2 pt. example. 

Some notes: 

This is from running the example as is - no changes to the .yml files, this is a check on whether or not it runs. 

This is in regards to issue #9 
parts: 
1) make sure example runs and produce chain
2) go through config file to understand what is what, also for output files
3) make sure we can submit an actual batch job

Notes: we can now run the example and produce chains using a batch job (Script included in this pull request). 

Looking at the results, needs some more tests to see if the outputs make sense. For this run it seems to have found a good fit to the clustering, but is highly offset for the cosmic shear and GG results.

### CODE REVIEW

**Comment by joezuntz** [comment]
@ellongley thanks - this looks great!  A few qns:
- it looks like some of the files were added accidentally, like the ipython notebook checkpoint.  
- are the various output_<long identifier> results intended also?

**Comment by joezuntz** [comment]
ack, just realised this is on txpipe-reanalysis not TXPipe itself, so having the results there makes more sense!

**Comment by chihway** [comment]
sent you comments through slack, copying here:

Thanks so much for the PR and for playing with firecrown. How long did you run the chain for? still looks kinda bad and not converged, hmm. For the data points, can you also plot the error bars? 

Also, yeah same as comment above, should remove the extra files and just keep the notebook and batch submission script?

**Comment by ellongley** [comment]
Notes / changes: 
1) Cleaned up the files that are included. 
2) Added error bars - I'm confused by the errors for xim and xip, I took the square root of the diagonal of the covariance matrix that was saved in the SACC file, they are clearly off for those quantities (plotted). 
3) I ran this just for 1000 which was the number given from the Firecrown example file, starting a new run to go for longer.

**Comment by ellongley** [comment]
Covariance issue resolved with https://github.com/LSSTDESC/firecrown/issues/90, will rerun with the changes.

**Pull request merged**
